"""HypothesisEngine: types, parsing, evaluator loops, and message assembly."""

from __future__ import annotations

import json
import logging
from collections.abc import Callable
from typing import Any

from pydantic import BaseModel, Field

from commit_investigator.hypothesis.hypothesis_prompts import (  # noqa: F401
    COVERAGE_SECTION_HEADER,
    HYPOTHESIS_SYSTEM_PROMPT,
    HYPOTHESIS_SYSTEM_PROMPT_CONTRASTIVE,
    HYPOTHESIS_SYSTEM_PROMPT_SYMPTOM_FIRST_WITH_EVALUATOR,
    PRODUCTION_SOURCE_SUFFIXES,
    extract_coverage_section,
    is_production_source_file,
)

try:
    from commit_investigator.hypothesis.historical_rag import get_historical_defect_context as _get_historical_defect_context
    _HISTORICAL_DEFECT_CONTEXT_AVAILABLE = True
except ImportError:
    _HISTORICAL_DEFECT_CONTEXT_AVAILABLE = False
from commit_investigator.context.context_builder import InvestigationContext
from commit_investigator.infra.llm import CursorSDKProvider, LLMMessage, LLMProvider, LLMResponse
from commit_investigator.context.smart_diff import AssembledDiff

logger = logging.getLogger(__name__)


class HypothesisSpec(BaseModel):
    """A single defect hypothesis generated by the LLM."""

    mechanism: str = Field(description="Failure mode description: If X then Y at file:area")
    evidence_quote: str = Field(default="", description="Exact diff line(s) supporting this hypothesis")
    file: str = Field(default="", description="Primary file this hypothesis concerns")
    lines: list[int] = Field(default_factory=list, description="[start_line, end_line] optional")
    suggested_action: str = Field(
        default="",
        description="What to verify or fix if this hypothesis is confirmed (1 sentence)",
    )


class HypothesisResponse(BaseModel):
    """LLM output: a list of defect hypotheses with a summary."""

    summary: str = Field(description="1-2 sentence description of what changed")
    hypotheses: list[HypothesisSpec] = Field(
        default_factory=list,
        description="List of specific failure mode hypotheses",
    )


def parse_hypothesis_response(raw: str) -> HypothesisResponse:
    """Parse LLM output into HypothesisResponse, tolerating markdown fences.

    Raises json.JSONDecodeError if no JSON object is found.
    """
    from commit_investigator.hypothesis.response_parser import extract_json

    data = extract_json(raw)
    if not data:
        raise json.JSONDecodeError("No JSON object found", raw, 0)
    return HypothesisResponse.model_validate(data)


def complete_with_parse_retry(
    llm: LLMProvider,
    messages: list[LLMMessage],
    tools_openai: list[dict[str, Any]] | None,
    parse_fn: Callable[[LLMResponse], HypothesisResponse],
    record_fn: Callable[[LLMResponse], None],
    parse_error: type[Exception],
) -> tuple[HypothesisResponse, LLMResponse]:
    """Call LLM and parse HypothesisResponse; retry once on parse failure (EC-1)."""
    for attempt in range(2):
        response = llm.complete(messages=messages, tools=tools_openai, temperature=0.0)
        record_fn(response)
        try:
            return parse_fn(response), response
        except parse_error as exc:
            if attempt == 0:
                messages.append(LLMMessage(
                    role="user",
                    content=(
                        f"Schema validation failed: {exc}. "
                        "Return valid JSON with 'summary' and 'hypotheses' fields only."
                    ),
                ))
                continue
            raise
    raise parse_error("No LLM response received")  # pragma: no cover


def has_changed_line_citation(evidence_quote: str) -> bool:
    """Return True if evidence_quote cites at least one +/- changed diff line."""
    for line in evidence_quote.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("+++") or stripped.startswith("---"):
            continue
        if stripped[0] in "+-":
            return True
    return False


def _ungrounded_primary_hypotheses(response: HypothesisResponse) -> list[HypothesisSpec]:
    """Return primary hypotheses (first 3) with non-empty context-only evidence quotes."""
    ungrounded: list[HypothesisSpec] = []
    for hyp in response.hypotheses[:3]:
        if hyp.evidence_quote.strip() and not has_changed_line_citation(hyp.evidence_quote):
            ungrounded.append(hyp)
    return ungrounded


def _build_mechanism_challenge(ungrounded: list[HypothesisSpec]) -> str:
    """Build a user message challenging context-only evidence citations."""
    lines = [
        "Mechanism evidence must cite at least one +/- changed diff line (not context-only).",
        "Revise the following primary hypotheses with evidence_quote containing a + or - line:",
    ]
    for hyp in ungrounded:
        lines.append(f"- mechanism: {hyp.mechanism!r}")
    return "\n".join(lines)


def mechanism_evaluator_loop(
    llm: LLMProvider,
    messages: list[LLMMessage],
    tools_openai: list[dict[str, Any]] | None,
    parse_fn: Callable[[LLMResponse], HypothesisResponse],
    record_fn: Callable[[LLMResponse], None],
    parse_error: type[Exception],
) -> tuple[HypothesisResponse, LLMResponse]:
    """T3 evaluator loop: grounded changed-line evidence, max 2 rounds.

    Uses Agent.create()+agent.send() multi-turn when the provider supports it
    (CursorSDKProvider), so the challenge lands as a real follow-up message
    rather than being embedded as conversation text in a one-shot prompt.
    Falls back to sequential complete() calls for other providers.
    """
    supports_multi_turn = isinstance(llm, CursorSDKProvider)

    if supports_multi_turn:
        return _mechanism_evaluator_loop_multi_turn(
            llm, messages, parse_fn, record_fn, parse_error,
        )
    return _mechanism_evaluator_loop_single(
        llm, messages, tools_openai, parse_fn, record_fn, parse_error,
    )


def _mechanism_evaluator_loop_multi_turn(
    llm: CursorSDKProvider,
    messages: list[LLMMessage],
    parse_fn: Callable[[LLMResponse], HypothesisResponse],
    record_fn: Callable[[LLMResponse], None],
    parse_error: type[Exception],
) -> tuple[HypothesisResponse, LLMResponse]:
    """T3 via Agent.create()+agent.send() — challenge is a real follow-up turn."""
    turns: list[list[LLMMessage]] = [messages]
    responses = llm.complete_multi_turn(turns[:1])
    llm_response = responses[0]
    record_fn(llm_response)

    try:
        parsed = parse_fn(llm_response)
    except parse_error as exc:
        logger.warning("T3 round 1 parse failed: %s — retrying in same session", exc)
        retry_msg = LLMMessage(
            role="user",
            content=(
                f"Schema validation failed: {exc}. "
                "Return valid JSON with 'summary' and 'hypotheses' fields only."
            ),
        )
        retry_responses = llm.complete_multi_turn([[retry_msg]])
        llm_response = retry_responses[0]
        record_fn(llm_response)
        parsed = parse_fn(llm_response)

    ungrounded = _ungrounded_primary_hypotheses(parsed)
    if not ungrounded:
        logger.debug("T3 round 1: all primary hypotheses grounded — no challenge needed")
        return parsed, llm_response

    challenge_text = _build_mechanism_challenge(ungrounded)
    logger.info(
        "T3 round 1: %d ungrounded hypothesis(es) — sending challenge turn:\n%s",
        len(ungrounded), challenge_text,
    )

    challenge_responses = llm.complete_multi_turn([[LLMMessage(role="user", content=challenge_text)]])
    llm_response = challenge_responses[0]
    record_fn(llm_response)

    try:
        parsed = parse_fn(llm_response)
    except parse_error as exc:
        logger.warning("T3 round 2 parse failed: %s — returning round 1 result", exc)

    still_ungrounded = _ungrounded_primary_hypotheses(parsed)
    if still_ungrounded:
        logger.info(
            "T3 round 2: %d hypothesis(es) still ungrounded after challenge — accepting best effort",
            len(still_ungrounded),
        )
    else:
        logger.info("T3 round 2: all primary hypotheses grounded after challenge")

    return parsed, llm_response


def _mechanism_evaluator_loop_single(
    llm: LLMProvider,
    messages: list[LLMMessage],
    tools_openai: list[dict[str, Any]] | None,
    parse_fn: Callable[[LLMResponse], HypothesisResponse],
    record_fn: Callable[[LLMResponse], None],
    parse_error: type[Exception],
) -> tuple[HypothesisResponse, LLMResponse]:
    """T3 fallback for non-multi-turn providers: appends challenge to message list."""
    parsed: HypothesisResponse | None = None
    llm_response: LLMResponse | None = None

    for evaluator_round in range(2):
        parsed, llm_response = complete_with_parse_retry(
            llm, messages, tools_openai, parse_fn, record_fn, parse_error,
        )
        ungrounded = _ungrounded_primary_hypotheses(parsed)
        if not ungrounded:
            logger.debug("T3 round %d: all grounded", evaluator_round + 1)
            return parsed, llm_response

        if evaluator_round == 0:
            challenge = _build_mechanism_challenge(ungrounded)
            logger.info("T3 round 1 (single): %d ungrounded — appending challenge", len(ungrounded))
            messages.append(LLMMessage(role="user", content=challenge))
            continue
        break

    assert parsed is not None and llm_response is not None
    return parsed, llm_response


def _is_production_file(file_path: str) -> bool:
    """Return True when file is a production .java/.py path (not a *Test* file)."""
    if not file_path:
        return False
    basename = file_path.rsplit("/", 1)[-1]
    if "Test" in basename:
        return False
    return file_path.endswith(".java") or file_path.endswith(".py")


def _select_primary_sort_key(
    item: tuple[int, HypothesisSpec],
    *,
    any_grounded: bool,
) -> tuple[int, ...]:
    """Build stable sort key for select_primary_by_evidence."""
    index, hyp = item
    grounded = has_changed_line_citation(hyp.evidence_quote)
    citation_bit = 0 if grounded else 1
    if not any_grounded:
        return (citation_bit, index)
    is_production = 1 if _is_production_file(hyp.file) else 0
    return (citation_bit, -is_production, index, -len(hyp.evidence_quote))


def select_primary_by_evidence(
    hypotheses: list[HypothesisSpec],
) -> list[HypothesisSpec]:
    """Reorder hypotheses so the best grounded-evidence candidate appears first.

    When no candidate cites a changed line, preserves original order (stable sort).
    When at least one is grounded, uses composite scoring: citation, production
    file path, original index, then quote length (EC-3).
    """
    if len(hypotheses) <= 1:
        return list(hypotheses)
    any_grounded = any(
        has_changed_line_citation(hyp.evidence_quote) for hyp in hypotheses
    )
    scored = sorted(
        enumerate(hypotheses),
        key=lambda item: _select_primary_sort_key(item, any_grounded=any_grounded),
    )
    return [h for _, h in scored]


def generate_contrastive_hypotheses(
    llm: LLMProvider,
    messages: list[LLMMessage],
    tools_openai: list[dict[str, Any]] | None,
    parse_fn: Callable[[LLMResponse], HypothesisResponse],
    record_fn: Callable[[LLMResponse], None],
    parse_error: type[Exception],
) -> tuple[HypothesisResponse, LLMResponse]:
    """Generate contrastive hypotheses with diversity constraint.

    The diversity constraint lives in HYPOTHESIS_SYSTEM_PROMPT_CONTRASTIVE
    (caller must pass messages assembled with that prompt). Evidence-based
    selection is handled downstream by select_primary_by_evidence().
    Uses a single LLM call — no evaluator loop, ~$0 extra cost.
    """
    return complete_with_parse_retry(llm, messages, tools_openai, parse_fn, record_fn, parse_error)


def build_investigation_messages(
    context: InvestigationContext,
    system_prompt: str = HYPOTHESIS_SYSTEM_PROMPT,
) -> list[LLMMessage]:
    """Assemble the LLM message list for hypothesis generation.

    Uses the pre-assembled smart diff from context.truncation_metadata
    when available, falling back to context.diff.
    """
    context_parts = [f"## Commit: {context.commit_id}\n## Project: {context.project}\n"]
    missing_reasons = list(context.missing_reasons)

    if context.message:
        context_parts.append(f"## Commit Message\n{context.message.strip()}\n")

    if context.diff:
        diff_text = context.diff
        tm: AssembledDiff | None = context.truncation_metadata
        if tm and tm.truncated_files:
            diff_text += (
                f"\n... (smart-truncated: {len(tm.truncated_files)} file(s) omitted: "
                + ", ".join(tm.truncated_files) + ")"
            )
        context_parts.append(f"## Diff\n```\n{diff_text}\n```\n")

    if context.touched_files:
        context_parts.append(
            "## Touched Files\n" + "\n".join(f"- {f}" for f in context.touched_files)
        )

    file_history_lines = _format_file_histories(context)
    if file_history_lines:
        context_parts.append("## File History\n" + "\n".join(file_history_lines))
    else:
        missing_reasons.append("File history unavailable — no prior commit data for changed files")

    author_stats_text = _format_author_stats(context)
    if author_stats_text:
        context_parts.append("## Author Stats\n" + author_stats_text)
    else:
        missing_reasons.append("Author statistics unavailable — author not in training data")

    if context.csv_features:
        feature_lines = [f"  {k}: {v}" for k, v in sorted(context.csv_features.items())]
        context_parts.append("## Numeric Features\n" + "\n".join(feature_lines))

    if context.router_probability is not None:
        context_parts.append(f"## Router Prior\nrouter_probability: {context.router_probability:.3f}\n")

    # Historical defect-category priors (gated by enable flag; status for forensics)
    if not context.enable_historical_defect_context:
        context.historical_defect_context_status = "disabled"
    elif not _HISTORICAL_DEFECT_CONTEXT_AVAILABLE:
        context.historical_defect_context_status = "unavailable"
    else:
        try:
            hist_ctx = _get_historical_defect_context(context)
            if hist_ctx:
                context.historical_defect_context_status = (
                    "fallback" if "project-wide" in hist_ctx else "injected"
                )
                context_parts.append(f"## Historical Context\n{hist_ctx}")
            elif context.csv_features:
                context.historical_defect_context_status = "unavailable"
                missing_reasons.append("Historical context unavailable (no matching training data)")
            else:
                context.historical_defect_context_status = "unavailable"
        except Exception as exc:
            context.historical_defect_context_status = "unavailable"
            logger.warning(
                "historical defect context failed for %s: %s",
                context.commit_id,
                exc,
                exc_info=True,
            )

    context.missing_reasons = missing_reasons
    if missing_reasons:
        context_parts.append("## Missing Context\n" + "\n".join(f"- {r}" for r in missing_reasons))

    user_content = "\n\n".join(context_parts)
    return [
        LLMMessage(role="system", content=system_prompt),
        LLMMessage(role="user", content=user_content),
    ]


def _format_file_histories(context: InvestigationContext) -> list[str]:
    """Format file histories as markdown lines. Returns empty list if unavailable."""
    histories = context.file_histories
    if not histories:
        return []
    lines: list[str] = []
    for fpath, history in list(histories.items())[:5]:
        if not history:
            continue
        lines.append(f"### {fpath}")
        for entry in history[:5]:
            lines.append(f"  - {entry.commit_id[:8]} | {entry.date[:10]} | {entry.author} | {entry.message}")
    return lines


def _format_author_stats(context: InvestigationContext) -> str:
    """Format author stats as a markdown block. Returns empty string if unavailable."""
    s = context.author_stats
    if s is None:
        return ""
    return (
        f"- Author: {s.author}\n"
        f"- Total commits: {s.total_commits}\n"
        f"- Buggy rate: {s.buggy_rate:.2%}\n"
        f"- Avg files changed: {s.avg_files_changed:.1f}"
    )
