"""CR Analyzer models — Pydantic v2, single source of truth."""

from .bundle import (
    CmdbEdge,
    CmdbNode,
    CmdbSnapshot,
    CRBundle,
    Incident,
    ItsmRecord,
    PrScopeFlags,
    ScheduledWindow,
    ScheduleEntry,
    SlaDefinition,
)
from .enums import (
    ChangeType,
    FindingDimension,
    Recommendation,
    RiskCategory,
    Severity,
    SlaAnalysisMode,
)
from .findings import Finding, FindingEvidence
from .outputs import (
    AggregateSlaImpact,
    AnalysisCoverage,
    CabReport,
    CabSummary,
    CompletenessOutput,
    CrossCrConflict,
    DimensionSeverityCounts,
    DispositionBreakdown,
    HistoricalPatternOutput,
    IngestOutput,
    NormalizeOutput,
    ParsedMarkdown,
    ProcessingInfo,
    ScheduleSlaOutput,
    SchedulingConflict,
    SlaImpact,
)

__all__ = [
    "AggregateSlaImpact",
    "AnalysisCoverage",
    "CabReport",
    "CabSummary",
    "ChangeType",
    "CmdbEdge",
    "CmdbNode",
    "CmdbSnapshot",
    "CompletenessOutput",
    "CRBundle",
    "CrossCrConflict",
    "DimensionSeverityCounts",
    "DispositionBreakdown",
    "Finding",
    "FindingDimension",
    "FindingEvidence",
    "HistoricalPatternOutput",
    "Incident",
    "IngestOutput",
    "ItsmRecord",
    "NormalizeOutput",
    "ParsedMarkdown",
    "PrScopeFlags",
    "ProcessingInfo",
    "Recommendation",
    "RiskCategory",
    "ScheduledWindow",
    "ScheduleEntry",
    "ScheduleSlaOutput",
    "SchedulingConflict",
    "Severity",
    "SlaAnalysisMode",
    "SlaDefinition",
    "SlaImpact",
]
